FROM rabbitmq:3

RUN rabbitmq-plugins enable --offline rabbitmq_management
RUN rabbitmq-plugins enable --offline rabbitmq_mqtt
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf
COPY 99-management_agent.disable_metrics_collector.conf /etc/rabbitmq/conf.d

EXPOSE 15671 15672
EXPOSE 1883



# podman volume create -o device=/srv/rabbitmq/msg_stores -o=o=bind rabbitmq_data_vol
# /var/lib/rabbitmq/mnesia/rabbit@my-rabbit/msg_stores

# podman run -d --rm --hostname my-rabbit --name my-rabbit -v rabbitmq_data_vol:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit/msg_stores:Z --network host rabbitmq:3-my
# podman run -d --rm --hostname my-rabbit --name my-rabbit --network host rabbitmq:3-my

# podman generate systemd --new --files --name my-rabbit
# podman build -f Containerfile_rabbitmq -t rabbitmq:3-my .
# systemctl --user stop container-my-rabbit.service
# systemctl --user start container-my-rabbit.service

